/* Generated by pc/tools/gen_struct_swap.py. */
#ifndef PC_YAKUMONO_SWAP_H
#define PC_YAKUMONO_SWAP_H

void pc_swap_yakumono_grbattle(void* p);
void pc_swap_yakumono_grbigblue(void* p);
void pc_swap_yakumono_grbigblueroute(void* p);
void pc_swap_yakumono_grcastle(void* p);
void pc_swap_yakumono_grcorneria(void* p);
void pc_swap_yakumono_grfigureget(void* p);
void pc_swap_yakumono_grflatzone(void* p);
void pc_swap_yakumono_grfourside(void* p);
void pc_swap_yakumono_grgarden(void* p);
void pc_swap_yakumono_grgreatbay(void* p);
void pc_swap_yakumono_grgreens(void* p);
void pc_swap_yakumono_grheal(void* p);
void pc_swap_yakumono_gricemt(void* p);
void pc_swap_yakumono_grinishie1(void* p);
void pc_swap_yakumono_grinishie2(void* p);
void pc_swap_yakumono_grizumi(void* p);
void pc_swap_yakumono_grkinokoroute(void* p);
void pc_swap_yakumono_grkongo(void* p);
void pc_swap_yakumono_grkraid(void* p);
void pc_swap_yakumono_grmutecity(void* p);
void pc_swap_yakumono_groldkongo(void* p);
void pc_swap_yakumono_groldpupupu(void* p);
void pc_swap_yakumono_groldyoshi(void* p);
void pc_swap_yakumono_gronett(void* p);
void pc_swap_yakumono_grpstadium(void* p);
void pc_swap_yakumono_grpushon(void* p);
void pc_swap_yakumono_grrcruise(void* p);
void pc_swap_yakumono_grshrineroute(void* p);
void pc_swap_yakumono_grstory(void* p);
void pc_swap_yakumono_grtfalco(void* p);
void pc_swap_yakumono_grtfox(void* p);
void pc_swap_yakumono_grtganon(void* p);
void pc_swap_yakumono_grtmewtwo(void* p);
void pc_swap_yakumono_grtpurin(void* p);
void pc_swap_yakumono_grvenom(void* p);
void pc_swap_yakumono_gryorster(void* p);
void pc_swap_yakumono_grzebes(void* p);
void pc_swap_yakumono_grzebesroute(void* p);

#endif
